name: betterchips
description: A better, more complete poker helper.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  adaptive_breakpoints: ^0.1.1
  animations: ^2.0.2
  collection: ^1.16.0
  cupertino_icons: ^1.0.4
  dual_screen: ^1.0.3
  flutter_gallery_assets: ^1.0.2
  flutter_localized_locales: ^2.0.3
  flutter_staggered_grid_view: ^0.6.1
  google_fonts: ^3.0.1
  intl: ^0.17.0
  meta: ^1.7.0
  package_info_plus: ^1.4.2
  path_provider: ^2.0.11
  provider: ^6.0.2
  rally_assets: ^3.0.1
  scoped_model: ^2.0.0
  shared_preferences: ^2.0.15
  shrine_images: ^2.0.1
  url_launcher: ^6.1.2
  vector_math: ^2.1.2
  firebase_core: ^1.22.0
  firebase_database: ^9.1.4
  firebase_auth: ^3.4.2



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.







  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages


flutter:
  deferred-components:
    - name: crane
      libraries:
        # Only one library from the loading unit is necessary.
        - package:gallery/studies/crane/app.dart
      assets:
        - packages/flutter_gallery_assets/crane/destinations/eat_1.jpg
        - packages/flutter_gallery_assets/crane/destinations/eat_2.jpg
        - packages/flutter_gallery_assets/crane/destinations/eat_3.jpg
        - packages/flutter_gallery_assets/crane/destinations/eat_4.jpg
        - packages/flutter_gallery_assets/crane/destinations/eat_5.jpg
        - packages/flutter_gallery_assets/crane/destinations/eat_6.jpg
        - packages/flutter_gallery_assets/crane/destinations/eat_7.jpg
        - packages/flutter_gallery_assets/crane/destinations/eat_8.jpg
        - packages/flutter_gallery_assets/crane/destinations/eat_9.jpg
        - packages/flutter_gallery_assets/crane/destinations/eat_10.jpg
        - packages/flutter_gallery_assets/crane/destinations/fly_0.jpg
        - packages/flutter_gallery_assets/crane/destinations/fly_1.jpg
        - packages/flutter_gallery_assets/crane/destinations/fly_2.jpg
        - packages/flutter_gallery_assets/crane/destinations/fly_3.jpg
        - packages/flutter_gallery_assets/crane/destinations/fly_4.jpg
        - packages/flutter_gallery_assets/crane/destinations/fly_5.jpg
        - packages/flutter_gallery_assets/crane/destinations/fly_6.jpg
        - packages/flutter_gallery_assets/crane/destinations/fly_7.jpg
        - packages/flutter_gallery_assets/crane/destinations/fly_8.jpg
        - packages/flutter_gallery_assets/crane/destinations/fly_9.jpg
        - packages/flutter_gallery_assets/crane/destinations/fly_10.jpg
        - packages/flutter_gallery_assets/crane/destinations/fly_11.jpg
        - packages/flutter_gallery_assets/crane/destinations/fly_12.jpg
        - packages/flutter_gallery_assets/crane/destinations/fly_13.jpg
        - packages/flutter_gallery_assets/crane/destinations/sleep_0.jpg
        - packages/flutter_gallery_assets/crane/destinations/sleep_1.jpg
        - packages/flutter_gallery_assets/crane/destinations/sleep_2.jpg
        - packages/flutter_gallery_assets/crane/destinations/sleep_3.jpg
        - packages/flutter_gallery_assets/crane/destinations/sleep_4.jpg
        - packages/flutter_gallery_assets/crane/destinations/sleep_5.jpg
        - packages/flutter_gallery_assets/crane/destinations/sleep_6.jpg
        - packages/flutter_gallery_assets/crane/destinations/sleep_7.jpg
        - packages/flutter_gallery_assets/crane/destinations/sleep_8.jpg
        - packages/flutter_gallery_assets/crane/destinations/sleep_9.jpg
        - packages/flutter_gallery_assets/crane/destinations/sleep_10.jpg
        - packages/flutter_gallery_assets/crane/destinations/sleep_11.jpg
        - packages/flutter_gallery_assets/crane/logo/logo.png
        - packages/flutter_gallery_assets/fonts/google_fonts/Raleway-Medium.ttf
        - packages/flutter_gallery_assets/fonts/google_fonts/Raleway-SemiBold.ttf
        - packages/flutter_gallery_assets/fonts/google_fonts/Raleway-Regular.ttf
        - packages/flutter_gallery_assets/fonts/google_fonts/Raleway-Light.ttf

  assets:
    - packages/flutter_gallery_assets/assets/studies/shrine_card_dark.png
    - packages/flutter_gallery_assets/assets/studies/starter_card.png
    - packages/flutter_gallery_assets/assets/studies/starter_card_dark.png
    - packages/flutter_gallery_assets/assets/studies/fortnightly_card_dark.png
    - packages/flutter_gallery_assets/assets/studies/rally_card_dark.png
    - packages/flutter_gallery_assets/assets/studies/reply_card_dark.png
    - packages/flutter_gallery_assets/assets/studies/fortnightly_card.png
    - packages/flutter_gallery_assets/assets/studies/crane_card.png
    - packages/flutter_gallery_assets/assets/studies/shrine_card.png
    - packages/flutter_gallery_assets/assets/studies/crane_card_dark.png
    - packages/flutter_gallery_assets/assets/studies/rally_card.png
    - packages/flutter_gallery_assets/assets/studies/reply_card.png
    - packages/flutter_gallery_assets/assets/logo/flutter_logo.png
    - packages/flutter_gallery_assets/assets/logo/flutter_logo_color.png
    - packages/flutter_gallery_assets/assets/icons/cupertino/cupertino.png
    - packages/flutter_gallery_assets/assets/icons/material/material.png
    - packages/flutter_gallery_assets/assets/icons/reference/reference.png
    - packages/flutter_gallery_assets/assets/demos/bottom_navigation_background.png
    - packages/flutter_gallery_assets/fonts/GalleryIcons.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/Merriweather-Regular.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/Eczar-Regular.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/Montserrat-Medium.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/Rubik-Bold.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/Merriweather-Light.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/RobotoCondensed-Bold.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/LibreFranklin-Regular.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/RobotoMono-Regular.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/LibreFranklin-ExtraBold.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/LibreFranklin-Bold.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/Oswald-SemiBold.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/Oswald-Medium.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/LibreFranklin-SemiBold.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/Montserrat-Bold.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/Merriweather-BoldItalic.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/Rubik-Medium.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/Montserrat-SemiBold.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/RobotoCondensed-Regular.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/LibreFranklin-Medium.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/Montserrat-Regular.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/Rubik-Regular.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/Eczar-SemiBold.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/WorkSans-Regular.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/WorkSans-Medium.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/WorkSans-Bold.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/WorkSans-Thin.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/WorkSans-SemiBold.ttf
    - packages/flutter_gallery_assets/fortnightly/fortnightly_army.png
    - packages/flutter_gallery_assets/fortnightly/fortnightly_bees.jpg
    - packages/flutter_gallery_assets/fortnightly/fortnightly_chart.png
    - packages/flutter_gallery_assets/fortnightly/fortnightly_fabrics.png
    - packages/flutter_gallery_assets/fortnightly/fortnightly_feminists.jpg
    - packages/flutter_gallery_assets/fortnightly/fortnightly_gas.png
    - packages/flutter_gallery_assets/fortnightly/fortnightly_healthcare.jpg
    - packages/flutter_gallery_assets/fortnightly/fortnightly_stocks.png
    - packages/flutter_gallery_assets/fortnightly/fortnightly_title.png
    - packages/flutter_gallery_assets/fortnightly/fortnightly_war.png
    - packages/flutter_gallery_assets/reply/attachments/paris_1.jpg
    - packages/flutter_gallery_assets/reply/attachments/paris_2.jpg
    - packages/flutter_gallery_assets/reply/attachments/paris_3.jpg
    - packages/flutter_gallery_assets/reply/attachments/paris_4.jpg
    - packages/flutter_gallery_assets/reply/avatars/avatar_0.jpg
    - packages/flutter_gallery_assets/reply/avatars/avatar_1.jpg
    - packages/flutter_gallery_assets/reply/avatars/avatar_2.jpg
    - packages/flutter_gallery_assets/reply/avatars/avatar_3.jpg
    - packages/flutter_gallery_assets/reply/avatars/avatar_4.jpg
    - packages/flutter_gallery_assets/reply/avatars/avatar_5.jpg
    - packages/flutter_gallery_assets/reply/avatars/avatar_6.jpg
    - packages/flutter_gallery_assets/reply/avatars/avatar_7.jpg
    - packages/flutter_gallery_assets/reply/avatars/avatar_8.jpg
    - packages/flutter_gallery_assets/reply/avatars/avatar_9.jpg
    - packages/flutter_gallery_assets/reply/avatars/avatar_10.jpg
    - packages/flutter_gallery_assets/reply/avatars/avatar_express.png
    - packages/flutter_gallery_assets/reply/icons/twotone_add_circle_outline.png
    - packages/flutter_gallery_assets/reply/icons/twotone_delete.png
    - packages/flutter_gallery_assets/reply/icons/twotone_drafts.png
    - packages/flutter_gallery_assets/reply/icons/twotone_error.png
    - packages/flutter_gallery_assets/reply/icons/twotone_folder.png
    - packages/flutter_gallery_assets/reply/icons/twotone_forward.png
    - packages/flutter_gallery_assets/reply/icons/twotone_inbox.png
    - packages/flutter_gallery_assets/reply/icons/twotone_send.png
    - packages/flutter_gallery_assets/reply/icons/twotone_star_on_background.png
    - packages/flutter_gallery_assets/reply/icons/twotone_star.png
    - packages/flutter_gallery_assets/reply/icons/twotone_stars.png
    - packages/flutter_gallery_assets/reply/reply_logo.png
    - packages/flutter_gallery_assets/places/india_chennai_flower_market.png
    - packages/flutter_gallery_assets/places/india_thanjavur_market.png
    - packages/flutter_gallery_assets/places/india_tanjore_bronze_works.png
    - packages/flutter_gallery_assets/places/india_tanjore_market_merchant.png
    - packages/flutter_gallery_assets/places/india_tanjore_thanjavur_temple.png
    - packages/flutter_gallery_assets/places/india_pondicherry_salt_farm.png
    - packages/flutter_gallery_assets/places/india_chennai_highway.png
    - packages/flutter_gallery_assets/places/india_chettinad_silk_maker.png
    - packages/flutter_gallery_assets/places/india_tanjore_thanjavur_temple_carvings.png
    - packages/flutter_gallery_assets/places/india_chettinad_produce.png
    - packages/flutter_gallery_assets/places/india_tanjore_market_technology.png
    - packages/flutter_gallery_assets/places/india_pondicherry_beach.png
    - packages/flutter_gallery_assets/places/india_pondicherry_fisherman.png
    - packages/flutter_gallery_assets/placeholders/avatar_logo.png
    - packages/flutter_gallery_assets/placeholders/placeholder_image.png
    - packages/flutter_gallery_assets/splash_effects/splash_effect_1.gif
    - packages/flutter_gallery_assets/splash_effects/splash_effect_2.gif
    - packages/flutter_gallery_assets/splash_effects/splash_effect_3.gif
    - packages/flutter_gallery_assets/splash_effects/splash_effect_4.gif
    - packages/flutter_gallery_assets/splash_effects/splash_effect_5.gif
    - packages/flutter_gallery_assets/splash_effects/splash_effect_6.gif
    - packages/flutter_gallery_assets/splash_effects/splash_effect_7.gif
    - packages/flutter_gallery_assets/splash_effects/splash_effect_8.gif
    - packages/flutter_gallery_assets/splash_effects/splash_effect_9.gif
    - packages/flutter_gallery_assets/splash_effects/splash_effect_10.gif
    - packages/rally_assets/logo.png
    - packages/rally_assets/thumb.png
    - packages/shrine_images/diamond.png
    - packages/shrine_images/slanted_menu.png
    - packages/shrine_images/0-0.jpg
    - packages/shrine_images/1-0.jpg
    - packages/shrine_images/2-0.jpg
    - packages/shrine_images/3-0.jpg
    - packages/shrine_images/4-0.jpg
    - packages/shrine_images/5-0.jpg
    - packages/shrine_images/6-0.jpg
    - packages/shrine_images/7-0.jpg
    - packages/shrine_images/8-0.jpg
    - packages/shrine_images/9-0.jpg
    - packages/shrine_images/10-0.jpg
    - packages/shrine_images/11-0.jpg
    - packages/shrine_images/12-0.jpg
    - packages/shrine_images/13-0.jpg
    - packages/shrine_images/14-0.jpg
    - packages/shrine_images/15-0.jpg
    - packages/shrine_images/16-0.jpg
    - packages/shrine_images/17-0.jpg
    - packages/shrine_images/18-0.jpg
    - packages/shrine_images/19-0.jpg
    - packages/shrine_images/20-0.jpg
    - packages/shrine_images/21-0.jpg
    - packages/shrine_images/22-0.jpg
    - packages/shrine_images/23-0.jpg
    - packages/shrine_images/24-0.jpg
    - packages/shrine_images/25-0.jpg
    - packages/shrine_images/26-0.jpg
    - packages/shrine_images/27-0.jpg
    - packages/shrine_images/28-0.jpg
    - packages/shrine_images/29-0.jpg
    - packages/shrine_images/30-0.jpg
    - packages/shrine_images/31-0.jpg
    - packages/shrine_images/32-0.jpg
    - packages/shrine_images/33-0.jpg
    - packages/shrine_images/34-0.jpg
    - packages/shrine_images/35-0.jpg
    - packages/shrine_images/36-0.jpg
    - packages/shrine_images/37-0.jpg

  generate: true
  uses-material-design: true
  fonts:
    - family: GalleryIcons
      fonts:
        - asset: packages/flutter_gallery_assets/fonts/GalleryIcons.ttf
